jobs:
  include:
    - language: java
      jdk: openjdk15
      script:
      - cd java && ant test

    - language: scala
      script:
      - cd scala && sbt test

    - language: python
      python: 2.7.8 
      script:
      - cd python && nosetests test

    - language: go
      script:
      - cd golang && go test -v src/merge/*.go

    - language: node_js
      node_js: 14.16.0
      script:
      - cd nodejs && && npm install && npm test

    - language: node_js
      node_js: 14.16.0
      script:
      - npm install --global gulp-cli
      - cd typescript && gulp default
        
    - language: node_js
      node_js: 14.16.0
      script:
      - cd react-js && yarn test && yarn build

    - language: rust
      script:
      - cd rust && cargo test
