before_script:
  -   - curl --create-dirs -L -o $HOME/.sbt/launchers/0.13.17/sbt-launch.jar https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/sbt-launch.jar
script: "./build.sh"

